<a href="https://colab.research.google.com/github/sahithik070/CRT-INTERNSHIP/blob/main/email_spam_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data = pd.read_csv("/content/spam (1).csv", encoding = "ISO-8859-1")
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [3]:
for col in data.columns:
    if 'Unnamed' in col:
        del data[col]
data.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
data.columns = ['Category','Message']
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.Message,data.Category,test_size=0.2)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]
features = v.fit_transform(X_train)

print(X_train_count)

  (0, 2386)	2
  (0, 7473)	2
  (0, 7696)	5
  (0, 7379)	1
  (0, 3976)	1
  (0, 7472)	3
  (0, 6821)	3
  (0, 5857)	1
  (0, 1056)	1
  (0, 7415)	1
  (0, 3306)	2
  (0, 6700)	1
  (0, 2523)	1
  (0, 6861)	2
  (0, 7436)	3
  (0, 758)	2
  (0, 6938)	1
  (0, 6452)	1
  (0, 3340)	1
  (0, 6133)	1
  (0, 5757)	1
  (0, 7682)	1
  (0, 2685)	2
  (0, 3767)	1
  (0, 1641)	1
  :	:
  (4455, 7538)	1
  (4455, 3432)	1
  (4455, 4422)	1
  (4455, 2876)	1
  (4455, 3755)	2
  (4455, 7391)	2
  (4455, 3498)	2
  (4455, 7206)	1
  (4455, 4824)	1
  (4455, 392)	1
  (4455, 4233)	1
  (4455, 7598)	1
  (4455, 5611)	1
  (4455, 5759)	1
  (4455, 7168)	1
  (4455, 4673)	1
  (4456, 6821)	1
  (4456, 7415)	1
  (4456, 6452)	1
  (4456, 7412)	1
  (4456, 5599)	1
  (4456, 4939)	1
  (4456, 3215)	1
  (4456, 6333)	1
  (4456, 4044)	1

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

In [8]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array(['ham', 'spam'], dtype='<U4')

In [9]:
features_test = v.transform(X_test)
model.score(features_test,y_test)*100

98.11659192825111